matches:
- trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":cu"
    replace: "Cube Online"

  - trigger: ":rs"
    replace: "Response automations setup"

  - trigger: ":note"
    replace: "TYPE OF CALL: Customer Service \nWHO WITH: \nTONE: Friendly\nQUERY: \nNOTES: \nOUTCOME: "

  - trigger: ":line"
    replace: "Email to customer: \n \n_____________________________________________________________\n \nEmail from Customer: "

  - trigger: ":ph"
    replace: "1300 423 618"

  - trigger: ":vm"
    replace: "TYPE OF CALL: Outbound \nWHO WITH: N/A \nTONE: N/A \nQUERY:N/A \nNOTES:N/A \nOUTCOME: Voicemail Left "

  - trigger: ":in"
    replace: "TYPE OF CALL: Inbound \nWHO WITH: N/A \nTONE: Friendly \nQUERY:N/A \nNOTES:N/A \nOUTCOME: Sorted "

  - trigger: ":out"
    replace: "TYPE OF CALL: Outbound \nWHO WITH: N/A \nTONE: Friendly \nQUERY:N/A \nNOTES:N/A \nOUTCOME: Sorted "

  - trigger: ":zap"
    replace: "TYPE OF CALL: Automations \nCRM:  \nTESTED:  \nWHO WITH:  \nNOTES: "

  - trigger: ":cb"
    replace: "TYPE OF CALL: Customer Service \nWHO WITH: \nTONE: Friendly\nQUERY:Callback Request \nNOTES: \nOUTCOME: "

  - trigger: ":card"
    replace: "TYPE OF CALL: Customer Service \nWHO WITH: \nTONE: Friendly\nQUERY:Payments \nNOTES: \nOUTCOME:Updated Details "

  - trigger: ":cx"
    replace: "TYPE OF CALL: Customer Service \nWHO WITH: \nTONE: Neutral\nQUERY:CX Request \nNOTES: \nOUTCOME: "

  - trigger: ":esc"
    replace: "TYPE OF CALL: Escalation \nWHO WITH: \nTONE: Neutral\nQUERY: \nNOTES: \nOUTCOME:Resolved, with email confirmation "

  - trigger: ":web"
    replace: "TYPE OF CALL: Customer Service \nWHO WITH: \nTONE: Friendly\nQUERY:Websites \nNOTES: \nOUTCOME:Passed on to websites "

  - trigger: ":pvm"
    replace: "TYPE OF CALL: PRE OB \nWHO WITH: \nTONE: Friendly\nQUERY:Pre-onboarding \nNOTES:Already created logins \nOUTCOME:Sent pre-onboarding email "

  - trigger: ":mob"
    replace: "TYPE OF CALL: Missed Onboardings \nWHO WITH: N/A \nTONE: N/A\nQUERY:N/A \nNOTES:N/a \nOUTCOME:Voicemail Left "

  - trigger: ":jot"
    replace: "Eng/Rev Setup. GMB Access requested. Response automations set up. Login details Emailed. "

  - trigger: ":kr"
    replace: "If you have any further questions, please feel free to reply to this email or give our team a call on 1300 423 618. \n \nKind Regards,"

  - trigger: ":pre"
    replace: "\nLogins - Reviews/Engine Sent: Yes/No\nCan login: Yes/No\nBookmarked: Yes/No\nCan Access to GMB: Yes/No\nGMB verified: Yes/No\nGMB Access Provided: Yes/No\nNumber of People in Training: ( )\nWill Be in front of PC\nPlease Install Microsoft Teams on your PC/Zoom in Mac - prior to the meeting\nConfirmed OB date/time: Yes/No\n(For Managed GMB services) - Set up Review Responses: Yes/No\nBusiness Contact 1\nName:\nEmail address:\nContact Number:\nRole/Position:\nWhat does this contact manage:\nPreferred Time of Contact:"



  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"